### ISSUE TITLE
Check authorization

### ISSUE THREAD

**Issue by guidocimurro** [BirdyF/strava_flutter#20]
Hi BirdyF,

thank you for your package.

How coud I check the status of authorization *without* open a new webView if there is no auth?

Thank-you very much,

Roberto

**Comment by BirdyF** [comment]
Hi Roberto,

Not 100% sure to understand your question. 
But if you want to check the status of Authorization without calling auth() you can call any API function and check the fault property.

For instance you can call getStats(int id) and check returnStat.fault. 
I think if the authentication has not been done before error code should 401.

Does it answer to your question?

**Comment by guidocimurro** [comment]
Thank-you very much for your reply!
You totally answer to my question, but unfortunely I get an exception

> NoSuchMethodError (NoSuchMethodError: The method 'toLowerCase' was called on null.
> Receiver: null
> Tried calling: toLowerCase())

```
Future<bool> authorizeStrava() async {
    strava = Strava(true, secret);
    final result = await strava.getStats(my_id);
    print(result);
  }
```

Thank-you!

**Comment by BirdyF** [comment]
Ok. Clear. I will do some tests and will fix it.

**Comment by guidocimurro** [comment]
Thank-you, thank you very much!

**Comment by BirdyF** [comment]
Hi Roberto,
I pushed a new version (1.2.0+43) on pub.dev that should fix the problem for all the strava APIs.
If a strava API is called before auth is called , it should return the error code statusTokenNotKnownYet in fault.
Let me know if it is ok for you.

**Comment by guidocimurro** [comment]
Thank-you very much, but I'm still getting the same exception

> NoSuchMethodError (NoSuchMethodError: The method 'toLowerCase' was called on null.
> Receiver: null
> Tried calling: toLowerCase())

My code:

```
Future<bool> authorizeStrava() async {
    strava = Strava(true, secret);
    // final user = await strava.oauth(clientId, 'activity:write', secret, 'auto');
    // DetailedAthlete _athlete = await strava.getLoggedInAthlete();
    final result = await strava.getStats(my_id).catchError((onError) {
      print(onError);
    });
    print(result);
  }
```

I've updated pubspec.yaml, got updated package and run "flutter clean".

Thank-you.

**Comment by guidocimurro** [comment]
I'm thinking about your solution and I was probably unable to explain myself (shame on me for my English... :-)). 

I'm a newbie, but I think it could be useful a function like this one (pseudocode):

```
authOk = isAlreadyAuthorize();
if not authOk
  print('You are not authorized yet, click the button to do it now').
  // Open the browser to authorize only after a click/tap    
```

In other words, I would like to know if the user is already authorized and, if not, open the webView only if and when I want to do it.

Thank-you very much for your helping.

**Comment by BirdyF** [comment]
Hi Roberto,

Sorry for my mistake. I think that the problem mentioned earlier has been fixed.
Now in 1.20.0+44,  you can do: 

Stats _stats = await strava.getStats(32212);
 if (_stats.fault.statusCode == error.statusTokenNotKnownYet) { 
    print ('status code ${ _stats.fault.message}');
  }

Regarding your proposal, you can use any API function to check if authorization has been done before or not using fault.statusCode

**Comment by guidocimurro** [comment]
Thank-you very much!

Just one more question: can't I check after reboot the app, right?
Let me explain.
1. I authorize Strava.
2. Run getStats and get data.
3. Reboot app, run 
```
strava = Strava(true, secret)
await strava.getStats(MyID);
```
and still get statusTokenNotKnownYet also if the authorization was done.

May I manual check in shared_preferences, load refresh token and access token if any and check after done?

Or I'm missing something?

Thank-you very much in any case!

**Comment by BirdyF** [comment]
Hi Roberto,

OK. I think that I undestand now what you want!
You want to know if Auth has been done before (even in previous runs of the app). Right ? 
If you check refresh_token and access_token in shared preferences, you need also to check if the access_token is not expired.

**Comment by guidocimurro** [comment]
Perfect! Thank-you very much!

**Comment by BirdyF** [comment]
If you come up with a function to do it, feel free to do a pull request so it can be added to the package.
