### ISSUE TITLE
Conflict with the Strava app

### ISSUE THREAD

**Issue by haslinger** [BirdyF/strava_flutter#32]
This is most likely not an issue, that could be solved by strava_flutter, but I would like to share my current state of the following issue and ask for your opinions on it:

A user running my app, who has also installed Strava's app on an iPhone (OS Version 13.04), gets the "Authorize to Strava" dialog, but when he clicks on the "Authorize" button, a popup "Open in Strava" appears. By clicking "OK" the Strava app opens and no data is sent back to my app. Cancel repaints the Dialog, so we are in an endless loop. The only way to get the token back into my app is uninstalling the Strava app from the iPhone, run through my app and reinstall the Strava app.

It seems that the Strava app somehow hijacks the request or callback for sending the data back into my app. I would assume, that the Strava app would have to fix that behavior, but my knowledge with iPhone OS is very limited. So maybe that link assignment can be removed by the user on OS level. But I'm not sure. Any ideas or thoughts are appreciated.

Feel free to close this issue, if we can't influence or fix that.

**Comment by BirdyF** [comment]
Hi @haslinger 
Have you done the test yourself on iOS? 
I checked quickly on my iPhone and I dont see a way for the user to remove this link. 
If you want I can do the test on iOS 13.3.1.

**Comment by haslinger** [comment]
I currently don't have an iOS device at hand, but I got a screen recording from the user: 
https://send.firefox.com/download/2a4bc4fdc0e41815/#H1360P7qSo0deuYzIHmzPw

**Comment by BirdyF** [comment]
Thanks. I understand. 
I should be able to do some tests tomorrow on iOS and will let you know

**Comment by BirdyF** [comment]
I have done some tests on iOS using example and asking for upload, with the latest strava version (22/04/2020):
- iOS 12.1, after authentication  asking  "Open in "example" ? with cancel/ok
- iOS 13.3.1, after authentication asking  "Open in "strava"?" with cancel/ok

It is a problem on iOS13 because when you install your app and use it for the first time you need to deinstall Strava app to have it working. After that for later use you can have strava app installed.
But clearly it is a problem.

Not sure it is bug from the package.
I will check first on other apps if they have the same problem. If not I will see in the code if there is anything we can do.

**Comment by haslinger** [comment]
No worries, no stress, we have the work around ;-)
 
Btw - hope not to annoy you!, if you ever want to play with my app, it's open source, the repo is over there: https://github.com/3schweinehunde/encrateia , meta info (and screenshots) is at https://encrateia.informatom.com/ and I would be happy to give you credits on the team page, if you agree.

**Comment by BirdyF** [comment]
I think I found the problem: it is a conflict in urlscheme. strava_flutter uses "strava" as urlscheme like strava app. 
I will do more tests (iOS and Android) and will push a new version soon.

I will look in more details to encrateia, it seems to provide a lot of analysis!
Personally I am bicycle centric so not sure to be able to use it.
Sure you can credit me on the team page.

**Comment by BirdyF** [comment]
Hi @haslinger 
I pushed a new version (1.2.1+51) today that should fix the problem (tested on iOS12, 13 and Android 9).
Let me know if it is not fixing the problem from your side.

**Comment by haslinger** [comment]
Unfortunately, we got a new error message (I didn't change anything in the code, just updated the dependency.)

![IMG_6366 PNG](https://user-images.githubusercontent.com/1116624/80303009-cefcfe00-87ad-11ea-9031-4427dd721773.jpeg)

**Comment by BirdyF** [comment]
Have you changed the url scheme? 
Now it is not anymore "strava" but "stravaflutter"
Please check documentation below:
2 - Settings of the url scheme for Strava Authentication redirect url a) For Android Add the following lines in your AndroidManifest.xml (in android/app/src/)

> 

 
 <intent-filter>
    <action android:name="android.intent.action.VIEW" />  
    <category android:name="android.intent.category.DEFAULT" /> 
    <category android:name="android.intent.category.BROWSABLE" /> 
    <data android:scheme="stravaflutter" android:host="redirect" />    
    <data android:pathPattern="/.*" />   
</intent-filter>

> 

b) for iOS Add the following lines in your info.plist (in ios/Flutter/Runner/)

<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>stravaflutter</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>strava</string>
			</array>
		</dict>
	</array>

**Comment by haslinger** [comment]
Oh, thanks, my bad!

**Comment by haslinger** [comment]
Meanwhile, I updated the browser schema, still the error message persists: "Safari cannot open the page because the address is invalid". The url that is actually used (copied from Safari's address bar) is: 
```
https://www.strava.com/oauth/authorize?client_id=38103&redirect_uri=stravaflutter://redirect/&response_type=code&approval_prompt=auto&scope=activity:write,activity:read_all,profile:read_all,profile:write
```

**Comment by BirdyF** [comment]
OK I will do additional test from my tests and will you let you know

**Comment by BirdyF** [comment]
I pushed a new version +54. 
urlscheme is changed  from strava to stravaflutter.
<key>CFBundleURLSchemes</key>
			<array>
				<string>stravaflutter</string>
			</array>

I think it should fix your problem. 
Please let me know!

**Comment by haslinger** [comment]
The new version doesn't fix the issue. Looking into today's commits: These are only changes
in code formatting, I don't see the urlscheme change.

**Comment by BirdyF** [comment]
Sorry. I have modified the URL Scheme before this version but only locally!
I have not been able to reproduce the problem on iOS 13. 
Do you have the invalid address message  before or after the ‘open with example’ message ?

Can you check if ‘redirect’ is still in settings application on your Strava dashboard?

**Comment by haslinger** [comment]
Thank you for your continuous support!
Regarding timing of the message, I have no iOS device at hand this week, and the test user is no developer, so update on this topic will follow next week.
Double checking the callback domain: Yes, it's still "redirect".

**Comment by tunt-04098** [comment]
https://github.com/BirdyF/strava_flutter/blob/709b0af68f0e58846178c48c4282ee7bfaf62201/example/ios/Runner/Info.plist

Check here, the ios info.plist in example folder have set 'stravaflutter' but 'strava' on the docs

<key>CFBundleURLTypes</key> <array> <dict> <key>CFBundleTypeRole</key> <string>Editor</string> <key>CFBundleURLName</key> <string>stravaflutter</string> <key>CFBundleURLSchemes</key> <array> <string>stravaflutter</string> </array> </dict> </array>

**Comment by tunt-04098** [comment]
Btw, if i install two flutter app use the strava oauth. When redirect schema is call 'stravaflutter://redirect', which application can catch links?

**Comment by haslinger** [comment]
@tunt-04098 thanks! Works on the first device, testing with two more (other os versions), then I'll close the issue.

**Comment by BirdyF** [comment]
Hi @tunt-04098 

Regarding your question about 2 apps using strava_flutter, clearly a conflict will appear.
This answer to this question should be similar to issue 33 about custom url scheme. But I dont know the answer.

**Comment by haslinger** [comment]
Tested on all devices available, works fine!

**Comment by BirdyF** [comment]
Thanks @haslinger for the feedback.
I will update the documentation.

**Comment by BirdyF** [comment]
Hi @tunt-04098 
Testing on Chrome if 2 apps have the same urlscheme, Chrome will ask to select which app to open
