### ISSUE TITLE
Unsuccessful authorization with browser different than Chrome

### ISSUE THREAD

**Issue by etabakov** [BirdyF/strava_flutter#36]
On Android, trying to authorize with any different browser than Chrome (e.g. Firefox, Dolphin) results in unsuccessful authorization. User is redirected to the root page of the app with no valid tokens stored.

**Comment by etabakov** [comment]
When debugging, this callback is not called when using different browser than Chrome:

https://github.com/BirdyF/strava_flutter/blob/15e0da75514f5319803309e29a6d57d6c2abb63c/lib/API/Oauth.dart#L161-L182

**Comment by jens-s-dreyer** [comment]
I confirm this issue.
Authorization with default browser from Mi Ui stuck at "Strava_flutter: Running on iOS or Android".

This seems the last API output above the snippet posted by etabakov.
(with chrome browser everything works)

**Comment by etabakov** [comment]
Another observation: looks like with other browser after the user clicks the "Authorize" button on Strava - the Flutter application is restarted. While, with Chrome - the application is still alive and the callback above handles the request.

**Comment by BirdyF** [comment]
Hi @etabakov  @jens-s-dreyer 
Thanks for reporting the problem. I will do some tests on Android 9 using Firefox.
Problem should come from url_launcher.
Once I can reproduce the problem I will test also with the latest version of url_launcher (5.4.5).

**Comment by etabakov** [comment]
Thanks a lot! Let me know if I can help with anything.

**Comment by BirdyF** [comment]
I have done a quick test on Android 9 with latest version of Firefox and been able to reproduce the problem.
Moving to url_launcher: ^5.4.5  seems to fix the problem for me.
I pushed a new version 1.2.1+55 with the latest version of url_launcher. 
Let me know if it solves your problem.

**Comment by etabakov** [comment]
The problem still persists on my side. Actually, I had already `url_launcher: ^5.4.5` set in my pubspec.yml, so I was using the latest version of the package.

**Comment by BirdyF** [comment]
I have done additional tests using example.dart:
- Firefox 68.7.0
- Android 9 1st May 2019 on LG G6
And I have not been able to reproduce the error.
Could you give the versions of Android and Firefox you are using?

**Comment by etabakov** [comment]
- Firefox 68.7.0
- Android 10 emulator x86

**Comment by BirdyF** [comment]
Can you try on Android 9 emulator?
I will try on Android 10 emulator x86

My flutter doctor (using web channel for the moment)
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.2 19C57, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.2)
[✓] Connected device (2 available)

**Comment by BirdyF** [comment]
I have been able to reproduce the problem on Android x86 emulator.
After the authorization, Firefox is restarting example (or creating a new instance).
I will additional tests around url_launcher package and will let you know if there is any progress.

**Comment by BirdyF** [comment]
Hi @etabakov 

FYI, I filed an issue regarding url_launcher package
[issues/56690](https://github.com/flutter/flutter/issues/56690)
Maybe you could add a thumb up to this issue to try to get a bit more priority from Flutter tearm.

**Comment by jens-s-dreyer** [comment]
Thank you very much :-) both of you

**Comment by BirdyF** [comment]
Hi @etabakov  and @jens-s-dreyer 
Following the advice of Noel Mansour in [issues/56690](https://github.com/flutter/flutter/issues/56690), I changed launchmode from singleTop to singleInstance.
I pushed a new  version(+60) and for me it is working on Firefox.
Could you check that it is also working on browsers that you are interested?

**Comment by etabakov** [comment]
Hey @BirdyF, just updated to `^1.2.1+60` but no luck - still doesn't work for me on Firefox. My app restarts and the authorization is not successful. How can I help you troubleshoot that?

**Comment by BirdyF** [comment]
Have you changed launch mode in AndroidManifest.xml from singleTop to singleInstance as mentioned by Noel Mansour ?
Sorry it is not yet in the documentation of the package.
I will do additional tests today and will update the documentation

**Comment by etabakov** [comment]
Oh, my bad - I was about to ask about it, but totally forgot. It works now. Thanks a lot!
Any side effects I should be careful about from switching from singleTop to singleInstance?

**Comment by etabakov** [comment]
I can confirm authorization is working now with Firefox, Opera, and Dolphin.

**Comment by BirdyF** [comment]
Hi @etabakov,
Good to know it is working for you.
Not sure about the consequence ofhe launch mode change from SingleTop to SingleInstance.
We have to keep this in mind if problem occurs on authentication callback.
